# Generated by Django 3.2.7 on 2021-10-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_topic_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="views",
            new_name="views_count",
        ),
    ]
